### ISSUE TITLE
Connection Refused Error to the client

### ISSUE THREAD

**Issue by dhilipkumars** [pivotal-cf/cf-redis-release#12]
Hi Team!,

I followed the instructions and was able to successfully deploy redis as a service to my CF (bosh-light).

However when i try to use the instance via an app i get 'Connection Refused' Error 

Via go client
```
dial tcp 10.244.3.46:40470: connection refused
```

as well as via ruby client when i try to use the example ruby app.

```
2015-08-12T18:28:13.57-0400 [RTR/0]      OUT redis-example-app.10.244.0.34.xip.io - [12/08/2015:22:28:03 +0000] "POST /foo HTTP/1.1" 404 8 18 "-" "curl/7.35.0" 10.0.2.15:57640 x_forwarded_for:"192.168.50.1, 10.0.2.15" vcap_request_id:cd0c4d45-242a-403c-518a-ad543539275d response_time:10.032475076 app_id:384c6268-9ee1-4a36-a4fd-e69081c58d0b
2015-08-12T18:34:38.18-0400 [App/0]      ERR Redis::CannotConnectError - Error connecting to Redis on 10.244.3.46:40470 (ECONNREFUSED):
2015-08-12T18:34:38.18-0400 [App/0]      ERR /home/vcap/app/vendor/bundle/ruby/2.2.0/gems/redis-3.1.0/lib/redis/client.rb:309:in `rescue in establish_connection'
2015-08-12T18:34:38.18-0400 [App/0]      ERR /home/vcap/app/vendor/bundle/ruby/2.2.0/gems/redis-3.1.0/lib/redis/client.rb:304:in `establish_connection'
```
does this work with opensource CF(210)? If yes how do i debug further?

**Comment by benlaplanche** [comment]
Is the app pushed to CF?

Can you share the output of `cf env` for your application

Can you share the output of `cf security-group <name>` for each security group you have (you need to be admin)

As this is BOSH Lite, if you run the `bin/add-route` script can you connect direclty to the Redis instance from your desktop using the `redis cli`. You can get the credentials from `cf env` for your application.
This will look something like `redis-cli -h 10.244.3.46 -p 40470 -a password` then run a command like `info` once connected

**Comment by dhilipkumars** [comment]
Sorry for the delay in response, yes the problem was "security-group" setup. Once that was done it worked like a charm.  Closing the Issue.
